name: Push para fork QA no GitLab

on:
  push:
    branches:
      - "frontend/**"   # só dispara se for um branch do tipo frontend/<usuario>

jobs:
  push-to-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Git com usuário do commit
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Definir branch destino no fork QA
        id: setbranch
        run: |
          # Pega o nome do branch local sem o "refs/heads/"
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "branch_destino=${BRANCH_NAME}" >> $GITHUB_OUTPUT

      - name: Adicionar remote do fork QA
        run: |
          git remote add fork-qa https://oauth2:${{ secrets.GITLAB_QA_TOKEN }}@gitlab.com/SEU_GRUPO/projetofinalmaisprati_qa.git

      - name: Push para branch no fork QA
        run: |
          git push fork-qa HEAD:${{ steps.setbranch.outputs.branch_destino }}
